---
driver:
  name: vagrant
  synced_folders:
    - ["./", "/habitat/package"]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-2016
    driver_config:
      box: mwrock/Windows2016
      customize:
        memory: 2048
        cpus: 4
  - name: ubuntu-18.04


suites:
  - name: default
    run_list:
      - recipe[windows-habitat-no-docker::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    excludes:
      - ubuntu-18.04
  - name: linux
    run_list:
      - recipe[windows-habitat-no-docker::linux]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
    excludes:
      - windows-2016
